### ISSUE TITLE
Referenced video is private

### ISSUE THREAD

**Issue by Jannyboy313** [adjust/redismq#29]
The video that is used as reference to the speed of the application inside the readme is private.

**Comment by wellle** [comment]
What video?

**Comment by elmacnifico** [comment]
it was this one: https://youtu.be/_k0lxEETvgk?t=58

Not sure it's crucial to the function 🤣

**Comment by wellle** [comment]
Haha 😂 

@Jannyboy313: Feel free to open a PR to remove that reference :v:

I'll close this for now.

**Comment by Jannyboy313** [comment]
I have created a [pull request](https://github.com/adjust/redismq/pull/30) with a public youtube video that fits the narrative
